<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Coba extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Coba_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'coba/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'coba/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'coba/index.html';
            $config['first_url'] = base_url() . 'coba/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Coba_model->total_rows($q);
        $coba = $this->Coba_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'coba_data' => $coba,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'konten' => 'coba/coba_list',
        );
        $this->load->view('template', $data);
    }

    public function read($id)
    {
        $row = $this->Coba_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'namacoba' => $row->namacoba,
		'tanggalcoba' => $row->tanggalcoba,
	 'konten' => 'coba/coba_read'    );
            $this->load->view('template', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'konten' => 'coba/coba_form',
            'action' => site_url('coba/create_action'),
	    'id' => set_value('id'),
	    'namacoba' => set_value('namacoba'),
	    'tanggalcoba' => set_value('tanggalcoba'),
	);
        $this->load->view('template', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'namacoba' => $this->input->post('namacoba',TRUE),
		'tanggalcoba' => $this->input->post('tanggalcoba',TRUE),
	    );

            $this->Coba_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('coba'));
        }
    }

    public function update($id)
    {
        $row = $this->Coba_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'konten' => 'coba/coba_form',
                'action' => site_url('coba/update_action'),
		'id' => set_value('id', $row->id),
		'namacoba' => set_value('namacoba', $row->namacoba),
		'tanggalcoba' => set_value('tanggalcoba', $row->tanggalcoba),
	    );
            $this->load->view('template', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'namacoba' => $this->input->post('namacoba',TRUE),
		'tanggalcoba' => $this->input->post('tanggalcoba',TRUE),
	    );

            $this->Coba_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('coba'));
        }
    }

    public function delete($id)
    {
        $row = $this->Coba_model->get_by_id($id);

        if ($row) {
            $this->Coba_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('coba'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }

    public function _rules()
    {
	$this->form_validation->set_rules('namacoba', 'namacoba', 'trim|required');
	$this->form_validation->set_rules('tanggalcoba', 'tanggalcoba', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Coba.php */
/* Location: ./application/controllers/Coba.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator */
/* Dikembangkan oleh Fakrullah Maulana dan dibuat pada : 2019-08-06 20:03:22  */
/* http://harviacode.com  dan maulana.ninja*/